name: cta-oz
channels:
  - default
  - conda-forge
dependencies:
  - astropy
  - cython
  - gammapy
  - iminuit
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyterlab_launcher
  - matplotlib
  - numpy=1.15.1   # frozen for now due to bug in 1.15.3
  - pandas
  - scipy
  - setuptools
  - uncertainties
  - pyyaml
  - iminuit
